Repository KaanIsmet/mywebclass-simulation, pull requests merged in 2023-03, with the labels that each got.

#6 Added docker repo
  .github/workflows/publish.yml
  docker-compose.yml
Labels: bug

#7 Webdevelop
  src/bootstrap-5.0.2-dist/css/bootstrap-grid.css
  src/bootstrap-5.0.2-dist/css/bootstrap-grid.css.map
  src/bootstrap-5.0.2-dist/css/bootstrap-grid.min.css
  src/bootstrap-5.0.2-dist/css/bootstrap-grid.min.css.map
  src/bootstrap-5.0.2-dist/css/bootstrap-grid.rtl.css
  src/bootstrap-5.0.2-dist/css/bootstrap-grid.rtl.css.map
  src/bootstrap-5.0.2-dist/css/bootstrap-grid.rtl.min.css
  src/bootstrap-5.0.2-dist/css/bootstrap-grid.rtl.min.css.map
  src/bootstrap-5.0.2-dist/css/bootstrap-reboot.css
  src/bootstrap-5.0.2-dist/css/bootstrap-reboot.css.map
  src/bootstrap-5.0.2-dist/css/bootstrap-reboot.min.css
  src/bootstrap-5.0.2-dist/css/bootstrap-reboot.min.css.map
  src/bootstrap-5.0.2-dist/css/bootstrap-reboot.rtl.css
  src/bootstrap-5.0.2-dist/css/bootstrap-reboot.rtl.css.map
  src/bootstrap-5.0.2-dist/css/bootstrap-reboot.rtl.min.css
  src/bootstrap-5.0.2-dist/css/bootstrap-reboot.rtl.min.css.map
  src/bootstrap-5.0.2-dist/css/bootstrap-utilities.css
  src/bootstrap-5.0.2-dist/css/bootstrap-utilities.css.map
  src/bootstrap-5.0.2-dist/css/bootstrap-utilities.min.css
  src/bootstrap-5.0.2-dist/css/bootstrap-utilities.min.css.map
  src/bootstrap-5.0.2-dist/css/bootstrap-utilities.rtl.css
  src/bootstrap-5.0.2-dist/css/bootstrap-utilities.rtl.css.map
  src/bootstrap-5.0.2-dist/css/bootstrap-utilities.rtl.min.css
  src/bootstrap-5.0.2-dist/css/bootstrap-utilities.rtl.min.css.map
  src/bootstrap-5.0.2-dist/css/bootstrap.css
  src/bootstrap-5.0.2-dist/css/bootstrap.css.map
  src/bootstrap-5.0.2-dist/css/bootstrap.min.css
  src/bootstrap-5.0.2-dist/css/bootstrap.min.css.map
  src/bootstrap-5.0.2-dist/css/bootstrap.rtl.css
  src/bootstrap-5.0.2-dist/css/bootstrap.rtl.css.map
  src/bootstrap-5.0.2-dist/css/bootstrap.rtl.min.css
  src/bootstrap-5.0.2-dist/css/bootstrap.rtl.min.css.map
  src/bootstrap-5.0.2-dist/js/bootstrap.bundle.js
  src/bootstrap-5.0.2-dist/js/bootstrap.bundle.js.map
  src/bootstrap-5.0.2-dist/js/bootstrap.bundle.min.js
  src/bootstrap-5.0.2-dist/js/bootstrap.bundle.min.js.map
  src/bootstrap-5.0.2-dist/js/bootstrap.esm.js
  src/bootstrap-5.0.2-dist/js/bootstrap.esm.js.map
  src/bootstrap-5.0.2-dist/js/bootstrap.esm.min.js
  src/bootstrap-5.0.2-dist/js/bootstrap.esm.min.js.map
  src/bootstrap-5.0.2-dist/js/bootstrap.js
  src/bootstrap-5.0.2-dist/js/bootstrap.js.map
  src/bootstrap-5.0.2-dist/js/bootstrap.min.js
  src/bootstrap-5.0.2-dist/js/bootstrap.min.js.map
  src/content.html
  src/css/index.css
  src/css/style.css
  src/index.html
  src/privacy.html
  src/scss/styles.scss
  src/story.html
Labels: enhancement

#9 Added documentation table in productivity_log.md
  productivity_log.md
Labels: documentation

#11 Newchanges
  src/content.html
  src/css/style.css
  src/privacy.html
  src/scss/styles.scss
  src/story.html
Labels: enhancement

#5 1 start adding playwright tests
  .github/workflows/playwright_video_lighthouse_report.yml
  package-lock.json
  package.json
  tests/test.js
  tests/testMain.js
Labels: enhancement, good first issue

#17 Updated documentation table in productivity_log.md
  productivity_log.md
Labels: documentation

#18 13 run test
  tests/mywebclass_title.spec.js
  tests/testMain.js
Labels: enhancement

#19 Updated documentation table in productivity_log.md
  productivity_log.md
Labels: documentation

#31 25 make more tests
  tests/mywebclass_title.spec.js
Labels: bug, enhancement

#34 32 add more tests
  tests/mywebclass_title.spec.js
Labels: enhancement

#39 fixed the I am Employer button on career.htm
  src/career.html
Labels: bug

#41 updated the productivity_log.md
  productivity_log.md
Labels: documentation

#45 added padding and closing ul tag
  src/courses.html
  src/forum.html
Labels: enhancement

#46 35 add more tests
  tests/mywebclass_title.spec.js
Labels: bug, enhancement

#48 updated documentation
  productivity_log.md
Labels: documentation
